### ISSUE TITLE
Handling complex resources

### ISSUE THREAD

**Issue by AlexU75** [Onto-Med/top-api#140]
- integrate multiple fields of FHIR resources in the class 'Value': Map<String, Value> fields
- add new item type: Encounter

**Comment by ChristophB** [comment]
Could you please provide an example for `Value.fields`?

**Comment by AlexU75** [comment]
E.g. 'id' and 'class' for Encounter or 'dose' and 'rate' for MedicationAdministration.

**Comment by ChristophB** [comment]
Something like the following `Value`?

```json
{
  "dataType": "number",
  "fields": {
    "dosage.dose": 2
  }
}
```

**Comment by AlexU75** [comment]
Data type refers to the main value (this could be boolean for MedicationAdministration, for example). The values in the map are also of type 'Value' and can have different data types.

**Comment by AlexU75** [comment]
In Java the map has type <String, Value>, right?
