### ISSUE TITLE
Terminology Versions

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/top-api#155]
## Background
Terminologies are sometimes updated - some periodically, some only occasionally.

There are typically the following changes carried out in an update:

* **ADD** new code
* **REMOVE** code
* **MODIFY** code

There can be cases where domain experts need to decide manually how to apply a version update. For example, a code is removed and one or more new codes are added as a replacement.

It is unclear if there is a common practice in providing migrations or change sets for version updates. For instance, BfArM provides update lists for ICD-10-GM in CSV format (https://www.bfarm.de/DE/Kodiersysteme/Services/Downloads/_node.html)

## Implications for the TOP Framework
* The terminology version used should be saved in TOP, so that it is possible to see whether codes used are potentially outdated. (repository level vs. entity level)
* Problem: Codes from different versions in a model must be avoided!
* A terminology update could lead to changes in the codes in a model. This means that phenotypes must be updated. The old codes would still be included in the version history.
* Most changes between versions can probably be covered automatically with migrations or mappings (see previous section).

**Comment by RalphBln** [comment]
A quick investigation revealed a certain diversity in how creators of terminologies publish changes

- ICD-10  ✅
	-  two CSV tables containing codes and code labels of the current and the preceding version, respectively. Changes can easily be identified via diff.
	-  A CSV file with code transitions: old code, new code, and hints about about in which direction(s) automated transitions can be applied or not.
- OPS ✅
	-  like ICD-10, with  an additional flag indicating whether a new code requires a supplementary character (for laterality or diagnosis confidence)
- PZN ❌
	- no version-to-version mapping info
- ASK ❌
	- no version-to-version mapping info
- ATC ✅
	- an XML file containing a structural diff between ontology versions (additons and deletions of classes and (subClass) axioms)
	- not trivial to identify renamings 
- LOINC ✅
	-  A CSV file with mappings of deprecated codes to their new replacements.
- SNOMED
	- Several csv files with mapping information - needs further investigation

**Comment by RalphBln** [comment]
The imported terminologies already contain version information, which can also be retrieved via the OLS API. Adding it to the TOP data model should be straightforward.

**Comment by ChristophB** [comment]
Rebased branch `add-code-version-info` on main.
