### ISSUE TITLE
Querying for documents requires a data source

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/top-api#171]
There are currently some operations that request documents without specifying the data source to be used. As we want to support multiple data sources, the source ID needs to be added as an additional parameter.

**Comment by fmatthies** [comment]
We also want to squash the different endpoints into one -> `path params` will become `query param`.

**Comment by ChristophB** [comment]
> Do you think that this suffices, @ChristophB ?

This is looking good!

**Comment by fmatthies** [comment]
I close this issue now and create a pull request.
The refactoring of the other endpoints will be done within another branch.
